### ISSUE TITLE
Questão 4 e número dos exercícios

### ISSUE THREAD

**Issue by SeveroDeveloper** [dinadevs/portugol#1]
## Número dos exercícios
É muito show que você esteja indo além do que é pedido adicionando um contexto aos exercícios, por exemplo, a questão pedia para ler um número e um caractere, você transformou em idade e sexo. Porém, também dificulta entender qual programa é cada uma das questões. Por isso, minha sugestão é que você adicione no nome do arquivo (ex1-, ex2-), ou então coloque um comentário no início do código (// Ex 1, // Ex2). 😄 

## Questão 4
Na questão 4 está escrito:
> Faça um programa que declare uma variável lógica e **imprima essa variável**

E você fez um programa bem mais complexo de par ou ímpar, que trabalha com a variável lógica, estrutura de condição, matemática e tal. Ficou bacana, mas não cumpriu com o que é pedido "imprima essa variável" (a variável lógica). Pois ao invés dela, você está imprimindo a inteira:
	
	funcao inicio()
	{
		logico numInteiro
		inteiro  num	
		
		escreva("Digite um número : ")
		leia(num)	
		
		numInteiro = (num % 2 == 0) // AQUI VOCÊ ATRIBUI VALOR À VARIÁVEL LÓGICA

		se (numInteiro) // E AQUI USA ELA NA CONDIÇÃO
		escreva("O número ", num, " é par.") // PORÉM NA HORA DE IMPRIMIR, VOCÊ IMPRIME O NUM, INTEIRO
		senao
		escreva("O número ", num, " é impar.")
	}

Então, o desafio é ajustar o programa para imprimir a variável lógica e continuar fazendo sentido.
> Dica: ao invés de imprimir uma frase afirmativa, imprima uma pergunta com "?", aí dá para encaixar o valor lógico.

Outro ponto importante é o nome da variável "numInteiro" , para uma variável do tipo lógico não está muito apropriado. 🤔

**Comment by dinadevs** [comment]
Resolvido no b8e2d74079bfa3999b30dee69b964440cfa3c68a
